# -*- coding: utf-8 -*-
"""ExtractEmailID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19M0encpI25RtoynMOUs0IuCe5kOu857z
"""

def no_of_x_in_y(x, y):
    number = 0
    for i in y:
        if i == x:
            number = number + 1
    return number

def if_email(case):
    index_at_the_rate = 0
    index_dot = 0
    for i in range(0, len(case)):
        if case[i] == "@":
            index_at_the_rate = i
            break
    if no_of_x_in_y(".", case[index_at_the_rate:len(case)]) == 0:
        return 0
    if(len(case[0:index_at_the_rate])==0):
        return 0
    if no_of_x_in_y("@", case) != 1:
        return 0
    else:
        return 1

f = open("EmailAdd_SocProS.txt")
given_text = f.read()

a = given_text.split()
emails = []
for i in range(0, len(a)):
    present_case = a[i]
    if (if_email(present_case) == 1):
        emails.append(present_case)

print(len(emails))
print(len(emails)/500)
import xlwt
wb = xlwt.Workbook('EmailAdd_SocProS.xlsx')
worksheet=[]
print(int(len(emails)/500)+1)
for i in range(0,int(len(emails)/500)+1):
  row=0
  worksheet.append(wb.add_sheet('sheet'+str(i)))
  for email in emails[i*500:]:
    if(row==500):
      break
    worksheet[i].write(row,0,email)
    row=row+1

wb.save('EmailAdd_SocProS.xlsx')



